baseURL = "https://github.com/Raquel240517/my_launchx_blog"
languageCode = "en-us"
title = "Bitácora de Viaje de Raquel Sanchez"
theme = "hugo-winston-theme"
relativeURLs = true
canonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 3

[params]
  google_analytics_id = ""
  # Hey Explorer aquí pon tu twitter 👇
  twitter_handle = ""
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addFrame = true
  addDot = true
